#!/usr/bin/env bash

set -e

trap 'rm -rf $YTPLAY_CACHE_TMP' EXIT

preflight() {
    if ! [[ $BASH_VERSION =~ ^5.3+ ]]; then
        echo "Requires Bash verison 5.3+"
        exit 1
    fi

    local required=( vlc yt-dlp )
    for app in "${required[@]}"; do
        if [[ ! ${ which "$app"; } ]]; then
            echo "$app executable cannot be found."
            echo "install $app to use this script."
            exit 1
        fi
    done

    YTPLAY_CACHE_TMP="/tmp/YTPLAY_CACHE"
    YTPLAY_DIR="$HOME/.ytplay"
    YTPLAY_SUBSCRIPTIONS="$HOME/.ytplay/subscriptions"
    NUMBER=50
    SEARCH=()
    YTDLP_ARGS=()
    VLC_ARGS=()

    if [[ ! -d $YTPLAY_DIR ]]; then
        mkdir "$YTPLAY_DIR"
    fi

    if [[ ! -d $YTPLAY_CACHE ]] && [[ -v YTPLAY_CACHE ]]; then
        mkdir "$YTPLAY_CACHE"
    fi
    if [[ ! -d $YTPLAY_CACHE_TMP ]] && [[ -v YTPLAY_CACHE ]]; then
        mkdir "$YTPLAY_CACHE_TMP"
    fi

}

search() {
    local number="$1"; shift
    local s="$1"; shift
    local tmp
    if [[ -v CHANNEL_NAME ]]; then
        tmp="${ yt-dlp      \
            --flat-playlist \
            --print "%(id)s %(playlist_index)-3d %(title)s | %(duration_string)s" \
            "https://www.youtube.com/@${CHANNEL_NAME}/search?query=${s}"; }"
    else
        tmp="${ yt-dlp                               \
            --flat-playlist "ytsearch${number}:${s}" \
            --print "%(id)s %(playlist_index)-3d %(title)s | %(channel,uploader)s | %(duration_string)s"; }"
    fi
    mapfile -t SEARCH <<<"$tmp"
    for i in "${SEARCH[@]}"; do
        local name
        IFS=' ' read -r _ name <<<"${i}"
        echo "$name"
    done
}

play() {
    if ! [[ -v YTPLAY_CACHE ]]; then
        yt-dlp                                        \
            --remote-components ejs:github            \
            -f "bestvideo+bestaudio/best"             \
            "${YTDLP_ARGS[@]}"                        \
            -o - "https://www.youtube.com/watch?v=$1" \
            | vlc                                     \
            --network-caching=1000                    \
            --play-and-exit "${VLC_ARGS[@]}"          \
            - 2>/dev/null
        return
    fi

    if [[ -f "${YTPLAY_CACHE}/${1}.mp4" ]]; then
        vlc --play-and-exit "${VLC_ARGS[@]}" "${YTPLAY_CACHE}/$1.mp4" &>/dev/null
    else
        yt-dlp                                        \
            --remote-components ejs:github            \
            -f "bestvideo+bestaudio/best"             \
            "${YTDLP_ARGS[@]}"                        \
            -o - "https://www.youtube.com/watch?v=$1" \
            | tee "${YTPLAY_CACHE_TMP}/${1}.mp4"      \
            | vlc                                     \
            --network-caching=1000                    \
            --play-and-exit "${VLC_ARGS[@]}"          \
            - 2>/dev/null

        if [[ ${PIPESTATUS[0]} -eq 0 ]]; then
            cp "${YTPLAY_CACHE_TMP}/${1}.mp4" "${YTPLAY_CACHE}/" \
                && rm -rf "$YTPLAY_CACHE_TMP/${1}.mp4"
        else
           rm -f "$YTPLAY_CACHE_TMP/${1}.mp4"
        fi
    fi

}

usage() {
	cat <<-EOF
    Usage: ${0##*/} [-q QUERY] [-c CHANNEL_NAME] [-p VIDEO_ID] [-n NUMBER] [-r RATE] [-b BROWSER] [-f] [-h]

	A thin yt-dlp/vlc wrapper for searching and playing YouTube videos,
	with optional local caching.

	Options:
	  -q QUERY         Search YouTube for QUERY and prompt for a video to play.
      -c CHANNEL_NAME  Search a specific channel.
	  -p VIDEO_ID      Play a specific YouTube video by its ID.
	  -n NUMBER        Number of search results to fetch with -s (default: ${NUMBER}).
	  -r RATE          Playback rate passed to vlc's --rate option.
	  -b BROWSER       Read cookies from BROWSER via yt-dlp's
	                   --cookies-from-browser (e.g. chrome, firefox, safari).
	  -f               Play in fullscreen (vlc --fullscreen).
	  -h               Show this help message and exit.

	Environment:
	  YTPLAY_CACHE       Directory used to cache downloaded videos.
	                     If unset, videos are streamed and not cached.

	Examples:
	  ${0##*/} -n 10 -q "lofi hip hop"
	  ${0##*/} -f -r 1.5 -p dQw4w9WgXcQ
	  ${0##*/} -b firefox -q "talk"
      ${0##*/} -c "theesotericachannel" -q "platonism"
	EOF
}

main() {
    preflight

    local OPTIND OPTARG opt
    while getopts "q:p:n:r:b:c:fh" opt; do
        case "$opt" in
            r)
                VLC_ARGS+=( --rate "$OPTARG" )
                ;;

            f)
                VLC_ARGS+=( --fullscreen )
                ;;
            n)
                NUMBER="$OPTARG"
                ;;
            b)
                YTDLP_ARGS+=( --cookies-from-browser "$OPTARG" )
                ;;
            c)
                CHANNEL_NAME="$OPTARG"
                ;;
            q)
                local result="${ search $NUMBER "$OPTARG"; }"
                echo
                local choice
                while [[ $choice != "q" ]]; do
                    for line in "${result[@]}"; do
                        echo "$line"
                    done

                    echo "Choose a video to play: 'q' to quit, 'a' to play all"
                    read -r choice
                    if [[ $choice == "a" ]]; then
                        local id
                        for v in "${SEARCH[@]}"; do
                            IFS=' ' read -r id _ <<<"${v}"
                            play "$id"
                            wait
                        done
                    elif [[ $choice -gt 0 && $choice -le ${#SEARCH[@]} ]]; then
                        IFS=' ' read -r id _ <<<"${SEARCH[choice - 1]}"
                        play "$id"
                    else
                        exit
                    fi
                done
                ;;
            p) # play
                play "$OPTARG"
                exit 0
                ;;
            h)
                usage
                exit 0
                ;;
            *)
                echo "bad arg"
                usage
                exit 1
                ;;
        esac
    done
    #shift $((OPTIND - 1))
    play dQw4w9WgXcQ
}; main "$@"

